### ISSUE TITLE
A question about epoch time breakdown

### ISSUE THREAD

**Issue by eddiegaoo** [GATECH-EIC/BNS-GCN#1]
Dear author of BNS-GCN,

I have a question about the epoch time breakdown.
<img width="845" alt="截屏2022-05-20 23 37 10" src="https://user-images.githubusercontent.com/67420785/169563346-88359218-ae93-4f91-bb60-6f509b935294.png">
For the first time in the picture, is it the computation time or is it the total time of one training epoch?
 I have already added --no_eval argument. But the time breakdown results are still strange and seem not following the results in the paper. That's why I ask this question.
Thanks!

**Comment by ch-wan** [comment]
Thank you for your interest to BNS-GCN. It represents the total time of one training epoch.

**Comment by eddiegaoo** [comment]
Thanks for the reply. I will close the issue.
