### ISSUE TITLE
partition for paper100m

### ISSUE THREAD

**Issue by liecn** [GATECH-EIC/BNS-GCN#2]
Hi,

thanks for your help. I try to partition the large dataset paper100m. However, it has errors with the log below. Could you help resolve that? I am sure there is enough memory (~1T). Not sure if it is because there aren't GPU for this node. (If so, could you please share the partition results from paper100m? say 40 partitions?)

Converting to homogeneous graph takes 7.768s, peak mem: 227.382 GB
Illegal instruction

Thanks.

**Comment by ch-wan** [comment]
Thanks for your interest in BNS-GCN. I notice that a similar problem was reported in DGL (see [this](https://github.com/dmlc/dgl/issues/3910)) which was resolved by the latest DGL. As I have integrated my customized DGL into the master branch, BNS-GCN can be launched with DGL 0.9.0. Could you please reinstall DGL to see whether the problem can be fixed. Also, did you confront a similar problem on small datasets (e.g., Cora)? Let me know if the issue still exists. Thanks.

**Comment by liecn** [comment]
Thanks, it works. But I had no issues on small datasets (e.g., Reddit, product) before. BTW, can you share what changes you have made for your customization? 

Thanks

**Comment by ch-wan** [comment]
You may refer [this PR](https://github.com/dmlc/dgl/pull/3821) for details. Thanks.

**Comment by liecn** [comment]
Solved. Please use the latest version of dgl.
