### ISSUE TITLE
An inquiry when using multiple compute nodes

### ISSUE THREAD

**Issue by qhtjrmin** [GATECH-EIC/BNS-GCN#6]
Hi, I am interested in training using your BNS-GCN in a distributed environment. However, I have encountered some difficulties running the setup with just the `reddit_multi_node.sh `script. 
Could I get some guidance on how to properly configure the environment for distributed experiments?
Thanks for your help.

**Comment by ch-wan** [comment]
Hi, thank you for your interest to BNS-GCN. There are many issues that can cause the failure of launching multi-node training. Could you please share me with the error message? Simply launching `reddit_multi_node.sh` should not work as you need to specify some arguments for distributed training by following [this](https://github.com/GATECH-EIC/BNS-GCN?tab=readme-ov-file#run-with-multiple-compute-nodes).

If you are asking how to setup a distributed training environment, you have find the [official PyTorch tutorial](https://pytorch.org/docs/stable/distributed.html) helpful.

Thanks.

**Comment by ch-wan** [comment]
@qhtjrmin  I'm going to close this issue due to its inactivity. Please feel free to reopen it if the above response is not sufficient. Thanks.
