### ISSUE TITLE
您好，请问inductive的意义？？inductive_split中为什么验证集里面包含了训练集，而测试集里面包含了验证集和训练集？？？

### ISSUE THREAD

**Issue by onepiecewiley** [GATECH-EIC/BNS-GCN#7]
def inductive_split(g):
    g_train = g.subgraph(g.ndata['train_mask'])
    g_val = g.subgraph(g.ndata['train_mask'] | g.ndata['val_mask'])
    g_test = g
    return g_train, g_val, g_test

**Comment by ch-wan** [comment]
@onepiecewiley Thank you for your question. For inductive learning, training nodes are used for feature propagation in the validation process, but their outputs are not used for computing validation accuracy. A similar policy is applied to the test process. You may find these codes helpful: https://github.com/GATECH-EIC/BNS-GCN/blob/b4a48bdaf25212bfddce46ec84af0ca2e351be7a/train.py#L29-L32

**Comment by ch-wan** [comment]
@onepiecewiley I'm going to close this issue due to its inactivity. Please feel free to reopen it if you have additional questions. Thanks.
